apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      name: pod-1
      labels:
        app: deploy
    spec:
      containers:
      - name: container
        image: kubetm/init