# k delete pods --all

apiVersion: v1
kind: Pod
metadata:
  name: pod-1                                # Pod 이름 (고유해야 함)
  labels:
     app: pod                                # Service가 선택할 라벨 (app=pod)
spec:
  nodeSelector:                              
    kubernetes.io/hostname: k8s-worker1      # 특정 노드(k8s-worker1)에 Pod 스케줄링
  containers:
  - name: container
    image: kubetm/app                        # 애플리케이션 이미지
    ports:
    - containerPort: 8080                    # 컨테이너 내부에서 서비스할 포트

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2                                # 두 번째 Pod (다른 노드에 배포)
  labels:
     app: pod                                # 동일 라벨 → 같은 Service에 묶임
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker2      # 특정 노드(k8s-worker2)에 Pod 스케줄링
  containers:
  - name: container
    image: kubetm/app
    ports:
    - containerPort: 8080                    # 컨테이너 내부 포트 (Service targetPort와 매칭)

---