# -----------------------------------------------------------
# 기존 모든 Pod 및 Service 삭제
# -----------------------------------------------------------
# k delete pods --all
# k delete svc  --all

# -----------------------------------------------------------
# Pod 정의 (k8s-worker1 노드에 배포)
# -----------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: pod-1                                # Pod 이름
  labels:
     app: pod                                # Service와 매칭될 라벨
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1      # 특정 노드(k8s-worker1)에 스케줄링
  containers:
  - name: container
    image: kubetm/app                        # 컨테이너 이미지
    ports:
    - containerPort: 8080                    # 컨테이너 내부 포트

---
# -----------------------------------------------------------
# Pod 정의 (k8s-worker2 노드에 배포)
# -----------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: pod-2                                # Pod 이름
  labels:
     app: pod                                # Service와 매칭될 라벨
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-worker2      # 특정 노드(k8s-worker2)에 스케줄링
  containers:
  - name: container
    image: kubetm/app
    ports:
    - containerPort: 8080                    # 컨테이너 내부 포트

---
# -----------------------------------------------------------
# NodePort Service 정의 (기본 모드: Cluster → Pod 라우팅)
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc-2                                # Service 이름
spec:
  selector:
    app: pod                                 # app=pod 라벨을 가진 Pod들 연결
  ports:
  - port: 9000                               # Service가 노출할 포트 (ClusterIP)
    targetPort: 8080                         # Pod 컨테이너 내부 포트
    nodePort: 30001                          # NodePort (외부 접근 가능 포트)
  type: NodePort                             # Service 타입: NodePort

# 사용 예시 (Node IP + NodePort로 접근)
# curl 192.168.56.31:30001/hostname
# curl 192.168.56.32:30001/hostname

---
# -----------------------------------------------------------
# NodePort Service 정의 (externalTrafficPolicy=Local)
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc-2-external-traffic                 # Service 이름
spec:
  selector:
    app: pod                                 # app=pod 라벨을 가진 Pod들 연결
  ports:
  - port: 9000                               # Service 포트
    targetPort: 8080                         # Pod 포트
    nodePort: 30002                          # 외부 접근용 NodePort
  type: NodePort
  externalTrafficPolicy: Local               # 외부 요청을 로컬 노드의 Pod에만 전달

# 사용 예시 (Node IP + NodePort로 접근)
# curl 192.168.56.31:30002/hostname
# curl 192.168.56.32:30002/hostname
