# k delete pods --all

# -----------------------------------------------------------
# Pod의 IP는 휘발성이므로 Service를 통해 고정된 접근 경로를 제공
# ClusterIP 타입 Service는 Cluster 내부에서만 접근 가능
# Service는 여러 Pod와 연결 가능하며, 트래픽은 라운드 로빈으로 분산됨
# -----------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: svc-1-clusterip                      # Service 이름
spec:
  selector:
    app: pod                                 # 라벨이 app=pod인 Pod들을 자동으로 연결
  ports:
  - port: 9000                               # Service가 노출할 포트 (ClusterIP 기준)
    targetPort: 8080                         # 연결된 Pod들이 실제로 사용하는 포트

# -----------------------------------------------------------
# 사용 방법:
# Master Node에서 Service의 ClusterIP:9000 으로 접근
# 예) curl  <Service-IP>:9000/hostname
# 예) curl 10.111.85.132:9000/hostname
# Service가 연결된 Pod 중 하나에 랜덤하게 트래픽이 전달됨
# -----------------------------------------------------------
