# -----------------------------------------------------------
# 기존 모든 Pod 및 Service 삭제
# -----------------------------------------------------------
# k delete pods --all
# -----------------------------------------------------------
# NodePort Service 정의 (기본 모드: Cluster → Pod 라우팅)
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc-2-nodePort                       # Service 이름
spec:
  selector:
    app: pod                                 # app=pod 라벨을 가진 Pod들 연결
  ports:
  - port: 9000                               # Service가 노출할 포트 (ClusterIP)
    targetPort: 8080                         # Pod 컨테이너 내부 포트
    nodePort: 30001                          # NodePort (외부 접근 가능 포트)
  type: NodePort                             # Service 타입: NodePort

# 사용 예시 (Node IP + NodePort로 접근)
# curl 192.168.56.31:30001/hostname
# curl 192.168.56.32:30001/hostname
